### ISSUE TITLE
$ symbol on the Result Screen

### ISSUE THREAD

**Issue by MinecraftNight4** [Azn9/MDAccuracyIndicatorMod#1]
Seems like a var is missing or something, but an $ appears on the result.
![image](https://user-images.githubusercontent.com/42017416/219907240-88754900-4bc9-4add-8709-d9f71b902dca.png)

**Comment by Azn9** [comment]
Fixed on the latest release : https://github.com/Azn9/MDAccuracyIndicatorMod/releases/tag/v1.1.0
